name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.25-alpha
homepage: https://github.com/ThinkSimple/flutter_simple_shopify
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  graphql:
    git:
      url: https://github.com/yuraware/graphql-flutter.git
      path: packages/graphql
  hive: ^2.1.0
  json_serializable: ^6.1.4
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
